# Generated by Django 5.2.1 on 2025-06-28 09:11

import auction.models
import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('auction', '0001_initial'), ('auction', '0002_alter_bid_amount'), ('auction', '0003_usertype_splitcompensation_alter_bid_amount'), ('auction', '0004_remove_usertype_splitcompensation_usertype_feesplit'), ('auction', '0005_adminsettings_defaultauctionlength'), ('auction', '0006_auction_invoicenumber'), ('auction', '0007_remove_auction_invoicenumber1_auction_auctionnumber'), ('auction', '0008_rename_auctionnumber1_auction_auctionnumber_and_more'), ('auction', '0009_remove_auction_auctionnumber1_and_more'), ('auction', '0010_remove_auction_auctionnumber1_and_more'), ('auction', '0011_numbers_remove_auction_auctionnumber1_and_more'), ('auction', '0012_remove_auction_auctionnumber1_and_more'), ('auction', '0013_rename_numbers_number'), ('auction', '0014_remove_auction_auctionnumber1_and_more'), ('auction', '0015_rename_auctionnumber1_auction_auctionnumber_and_more'), ('auction', '0016_rename_auctionnumber1_auction_auctionnumber_and_more'), ('auction', '0017_rename_adminsettings_adminsetting'), ('auction', '0018_rename_auctionnumber1_auction_auctionnumber_and_more'), ('auction', '0019_rename_auctionnumber1_auction_auctionnumber_and_more'), ('auction', '0020_adminsetting_rename_numbers_number_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicName', models.CharField(blank=True, help_text='Enter the clinic name.', max_length=200, null=True, verbose_name='Clinic Name')),
                ('licenseNumber', models.CharField(blank=True, help_text='Enter you license number.', max_length=120, null=True, verbose_name='License Number')),
                ('imageOne', models.ImageField(blank=True, default='default.jpg', help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image One')),
                ('imageTwo', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image Two')),
                ('imageThree', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image Three')),
                ('imageFour', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image Four')),
                ('city', models.CharField(blank=True, help_text='Enter the city your clinic is in.', max_length=120, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, help_text='Enter the country your clinic is in.', max_length=100, null=True, verbose_name='Conutry')),
                ('province', models.CharField(blank=True, choices=[('', '---------'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut'), ('Yukon', 'Yukon')], help_text='The province the clinic resides in.', max_length=30, null=True, verbose_name='Province')),
                ('about', models.TextField(blank=True, help_text='Tell us about your clinic.', null=True, verbose_name='About the clinic')),
                ('underEighteen', models.IntegerField(blank=True, null=True, verbose_name='% Under 18')),
                ('eighteenToSixtyFive', models.IntegerField(blank=True, null=True, verbose_name='% 18 - 65')),
                ('overSixtyFive', models.IntegerField(blank=True, null=True, verbose_name='% Over 65')),
                ('MSK', models.IntegerField(blank=True, null=True, verbose_name='% Musculoskeletal')),
                ('neuro', models.IntegerField(blank=True, null=True, verbose_name='% Neurological')),
                ('cardioResp', models.IntegerField(blank=True, null=True, verbose_name='% Cardiorespiratory')),
                ('pro', models.BooleanField(blank=True, null=True, verbose_name='Pro Member')),
                ('remember_auction_data', models.BooleanField(blank=True, null=True, verbose_name='Do you want your data to be pre-populated for your next auction?')),
                ('auction_message_displayed', models.BooleanField(blank=True, null=True, verbose_name='Auction Message Displayed')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auctionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auctionStart', models.DateTimeField(help_text='Enter the start date of the auction.', verbose_name='Auction Start')),
                ('auctionEnd', models.DateTimeField(help_text='Enter the end date of the auction.', verbose_name='Auction End')),
                ('placementStart', models.DateField(default=datetime.date.today, help_text='Enter the start date of the placement.', verbose_name='Therapist Start Date')),
                ('placementEnd', models.DateField(default=datetime.date.today, help_text='Enter the end date of the placement.', verbose_name='Therapist End Date')),
                ('mondayStart', models.TimeField(blank=True, default='09:00', null=True, verbose_name='Start Time')),
                ('mondayEnd', models.TimeField(blank=True, default='17:00', null=True, verbose_name='End Time')),
                ('tuesdayStart', models.TimeField(blank=True, default='09:00', null=True, verbose_name='Start Time')),
                ('tuesdayEnd', models.TimeField(blank=True, default='17:00', null=True, verbose_name='End Time')),
                ('wednesdayStart', models.TimeField(blank=True, default='09:00', null=True, verbose_name='Start Time')),
                ('wednesdayEnd', models.TimeField(blank=True, default='17:00', null=True, verbose_name='End Time')),
                ('thursdayStart', models.TimeField(blank=True, default='09:00', null=True, verbose_name='Start Time')),
                ('thursdayEnd', models.TimeField(blank=True, default='17:00', null=True, verbose_name='End Time')),
                ('fridayStart', models.TimeField(blank=True, default='09:00', null=True, verbose_name='Start Time')),
                ('fridayEnd', models.TimeField(blank=True, default='17:00', null=True, verbose_name='End Time')),
                ('saturdayStart', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('saturdayEnd', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('sundayStart', models.TimeField(blank=True, null=True, verbose_name='Start Time')),
                ('sundayEnd', models.TimeField(blank=True, null=True, verbose_name='End Time')),
                ('reservePrice', models.IntegerField(blank=True, help_text='Reserve bid is the maximum price the clinic is willing to offer.', null=True, verbose_name='Reserve Price')),
                ('startingBid', models.IntegerField(blank=True, help_text='The intial bid amount.', null=True, verbose_name='Starting Bid')),
                ('minimumBidIncrement', models.IntegerField(blank=True, help_text='All bids must decrease by the minimum bid increment.', null=True, verbose_name='Minimum Bid Increment')),
                ('currentLowBid', models.IntegerField(blank=True, null=True, verbose_name='Current Low Bid')),
                ('winningPrice', models.IntegerField(blank=True, null=True, verbose_name='Winning Price')),
                ('underEightteen', models.IntegerField(blank=True, null=True, verbose_name='Under 18')),
                ('eightteenToSixtyFive', models.IntegerField(blank=True, null=True, verbose_name='18 - 65')),
                ('overSixtyFive', models.IntegerField(blank=True, null=True, verbose_name='Over 65')),
                ('MSK', models.IntegerField(blank=True, null=True, verbose_name='MSK')),
                ('neuro', models.IntegerField(blank=True, null=True, verbose_name='Neuro')),
                ('cardioResp', models.IntegerField(blank=True, null=True, verbose_name='CardioResp')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Information about the Clinic')),
                ('active', models.BooleanField(verbose_name='Active Auction')),
                ('closed', models.BooleanField(verbose_name='Closed Auction')),
                ('deleted', models.BooleanField(verbose_name='Deleted Auction')),
                ('cronID', models.TextField(verbose_name='Cron Job Timer ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified Time')),
                ('treatmentCost', models.IntegerField(blank=True, null=True, verbose_name='Treatment Cost')),
                ('treatmentMin', models.FloatField(blank=True, null=True, verbose_name='Minimum # of Treatments')),
                ('assessmentCost', models.IntegerField(blank=True, null=True, verbose_name='Assessment Cost')),
                ('assessmentMin', models.FloatField(blank=True, null=True, verbose_name='Minimum # of Assessments')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_clinic', to='auction.account')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a demographic type.', max_length=200, verbose_name='Demographic')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='Name of the page.', max_length=200, verbose_name='Page')),
            ],
        ),
        migrations.CreateModel(
            name='PayFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a pay frequency.', max_length=200, verbose_name='Pay Frequency')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a payment type from the list.', max_length=200, verbose_name='Payment Type')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a therapist type', max_length=200, verbose_name='Therapist Type')),
                ('feeSplit', models.BooleanField(default=False, help_text='If checked this user type will be allowed to select fee split as a payment type.', verbose_name='Allowed Fee Split')),
            ],
        ),
        migrations.CreateModel(
            name='ProMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proStart', models.DateTimeField(verbose_name='Start of Pro Membership')),
                ('proEnd', models.DateTimeField(blank=True, null=True, verbose_name='End of Pro Membership')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_member_clinic', to='auction.account')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAreaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a practice area.', max_length=200, verbose_name='Practice Area')),
                ('userType', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_user_type', to='auction.usertype')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(verbose_name='Percentage')),
                ('auction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_auction', to='auction.auction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_type', to='auction.practiceareatype')),
            ],
        ),
        migrations.CreateModel(
            name='PopupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message to be displayed in the popup.', max_length=5000, verbose_name='Popup Message')),
                ('active', models.BooleanField(help_text='Is the popup currently active.', verbose_name='Active')),
                ('title', models.CharField(help_text='The title of the popup box.', max_length=5000, verbose_name='Popup Box Title')),
                ('show_unauthenticated_users', models.BooleanField(help_text='Should the pop-up be shown to non-users.', verbose_name='Show to Non-logged in users')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_popup_message', to='auction.page')),
                ('clickID', models.CharField(blank=True, help_text='The ID for the item being clicked to trigger the pop-up. For non-clickable messages leave blank.', max_length=5000, null=True, verbose_name='Clickable Item ID')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(help_text='Has the popup been acknowledged.', verbose_name='Acknowledged')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_acknowledgement', to='auction.popupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_acknowledgement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(verbose_name='Percentage')),
                ('auction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demogrpahic_auction', to='auction.auction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auction.demographictype')),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='payFrequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_frequency', to='auction.payfrequency', verbose_name='Pay Frequency'),
        ),
        migrations.AddField(
            model_name='auction',
            name='paymentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_type', to='auction.paymenttype', verbose_name='Payment Type '),
        ),
        migrations.AddField(
            model_name='auction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_type', to='auction.usertype', verbose_name='Auction Type'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='demographic',
            field=models.ManyToManyField(blank=True, to='auction.demographic'),
        ),
        migrations.AddField(
            model_name='account',
            name='practiceArea',
            field=models.ManyToManyField(blank=True, to='auction.practicearea'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='userType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertypes', to='auction.usertype', verbose_name='User Type'),
        ),
        migrations.AddField(
            model_name='auction',
            name='auctionNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auction Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut'), ('Yukon', 'Yukon')], help_text='The province the clinic resides in.', max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='assessmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name="Clinic's Assessment Price"),
        ),
        migrations.AlterField(
            model_name='auction',
            name='assessmentMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Daily Minimum # of Assessments'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='treatmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name="Clinic's Treatment Price"),
        ),
        migrations.AlterField(
            model_name='auction',
            name='treatmentMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Daily Minimum # of Treatments'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='auction',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_auction', to='auction.auction'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_type', to='auction.practiceareatype'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reservePrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserve Price'),
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bidID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(blank=True, help_text='Enter the amount you would like to bid.', null=True, verbose_name='Amount1')),
                ('active', models.BooleanField(verbose_name='Active Bid')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified Time')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction.auction')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_created_by', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementEnd',
            field=models.DateField(default=datetime.date.today, help_text='Enter the end date of the placement.', verbose_name='Clinican End Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementStart',
            field=models.DateField(default=datetime.date.today, help_text='Enter the start date of the placement.', verbose_name='Clinican Start Date'),
        ),
        migrations.CreateModel(
            name='AdminSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendEmails', models.BooleanField(help_text='Turns on and off emails. If checked emails will send.', verbose_name='Send Emails')),
                ('numAllowedAuctions', models.IntegerField(help_text='Global setting for max number of active auctions', verbose_name='# Allowed Auctions')),
                ('defaultAuctionLength', models.IntegerField(help_text='Auctions will be set to this length, in seconds.', verbose_name='Default Auction Length in Seconds')),
                ('endAuctionEmailBatchSize', models.IntegerField(help_text='At the end of an auction emails will be sent to user with the same type as the auction. To avoid spamming email batches are limited to this number.', verbose_name='End of Auction Email Batch Size')),
            ],
        ),
        migrations.CreateModel(
            name='Number',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Cateogry for the number.', max_length=200, verbose_name='Cateogry')),
                ('currentValue', models.IntegerField(help_text="The counter's current value.", verbose_name='Current Counter Value')),
            ],
        ),
    ]
