# Generated by Django 4.0.4 on 2022-05-03 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinicName', models.CharField(blank=True, help_text='Enter the clinic name.', max_length=200, null=True, verbose_name='Clinic Name')),
                ('licenseNumber', models.CharField(blank=True, help_text='Enter you license number.', max_length=120, null=True, verbose_name='License Number')),
                ('imageOne', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to='images/', verbose_name='Clinic Image One')),
                ('imageTwo', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to='images/', verbose_name='Clinic Image Two')),
                ('imageThree', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to='images/', verbose_name='Clinic Image Three')),
                ('imageFour', models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to='images/', verbose_name='Clinic Image Four')),
                ('city', models.CharField(blank=True, help_text='Enter the city your clinic is in.', max_length=120, null=True, verbose_name='City')),
                ('country', models.CharField(blank=True, help_text='Enter the country your clinic is in.', max_length=100, null=True, verbose_name='Conutry')),
                ('about', models.TextField(blank=True, help_text='Tell us about your clinic.', null=True, verbose_name='About')),
                ('pro', models.BooleanField(blank=True, verbose_name='Pro Member')),
            ],
        ),
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('auctionID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auctionStart', models.DateTimeField(help_text='Enter the start date of the auction.', verbose_name='Auction Start')),
                ('auctionEnd', models.DateTimeField(help_text='Enter the end date of the auction.', verbose_name='Auction End')),
                ('placementStart', models.DateField(blank=True, help_text='Enter the start date of the placement.', null=True, verbose_name='Placement Start')),
                ('placementEnd', models.DateField(blank=True, help_text='Enter the end date of the placement.', null=True, verbose_name='Placement End')),
                ('mondayStart', models.TimeField(blank=True, help_text='Enter the start of the workday on Mondays.', null=True, verbose_name='Monday Start Time')),
                ('mondayEnd', models.TimeField(blank=True, help_text='Enter the end of the workday on Mondays.', null=True, verbose_name='Monday End Time')),
                ('tuesdayStart', models.TimeField(blank=True, help_text='Enter the start of the workday on Tuesdays.', null=True, verbose_name='Tuesday Start Time')),
                ('tuesdayEnd', models.TimeField(blank=True, help_text='Enter the end of the workday on Tuesdays.', null=True, verbose_name='Tuesday End Time')),
                ('wednesdayStart', models.TimeField(blank=True, help_text='Enter the start of the workday on Wednesdays.', null=True, verbose_name='Wednesday Start Time')),
                ('wednesdayEnd', models.TimeField(blank=True, help_text='Enter the end of the workday on Wednesdays.', null=True, verbose_name='Wednesday End Time')),
                ('thursdayStart', models.TimeField(blank=True, help_text='Enter the start of the workday on Thursdays.', null=True, verbose_name='Thursday Start Time')),
                ('thursdayEnd', models.TimeField(blank=True, help_text='Enter the end of the workday on Thursdays.', null=True, verbose_name='Thursday End Time')),
                ('fridayStart', models.TimeField(blank=True, help_text='Enter the start of the workday on Fridays.', null=True, verbose_name='Friday Start Time')),
                ('fridayEnd', models.TimeField(blank=True, help_text='Enter the end of the workday on Fridays.', null=True, verbose_name='Friday End Time')),
                ('saturdayStart', models.TimeField(blank=True, help_text='Enter the start of the workday on Saturdays.', null=True, verbose_name='Saturday Start Time')),
                ('saturdayEnd', models.TimeField(blank=True, help_text='Enter the end of the workday on Saturdays.', null=True, verbose_name='Saturday End Time')),
                ('sundayStart', models.TimeField(blank=True, help_text='Enter the start of the workday on Sundays.', null=True, verbose_name='Sunday Start Time')),
                ('sundayEnd', models.TimeField(blank=True, help_text='Enter the end of the workday on Sundays.', null=True, verbose_name='Sunday End Time')),
                ('reservePrice', models.IntegerField(help_text='Reserve bid is the maximum price the clinic is willing to offer.', verbose_name='Reserve Price')),
                ('startingBid', models.IntegerField(help_text='The intial bid amount.', verbose_name='Starting Bid')),
                ('minimumBidIncrement', models.IntegerField(help_text='All bids must decrease by the minimum bid increment.', verbose_name='Minimum Bid Increment')),
                ('currentLowBid', models.IntegerField(blank=True, null=True, verbose_name='Current Low Bid')),
                ('winningPrice', models.IntegerField(blank=True, null=True, verbose_name='Winning Price')),
                ('underEightteen', models.IntegerField(blank=True, null=True, verbose_name='Under 18')),
                ('eightteenToSixtyFive', models.IntegerField(blank=True, null=True, verbose_name='18 - 65')),
                ('overSixtyFive', models.IntegerField(blank=True, null=True, verbose_name='Over 65')),
                ('MSK', models.IntegerField(blank=True, null=True, verbose_name='MSK')),
                ('neuro', models.IntegerField(blank=True, null=True, verbose_name='Neuro')),
                ('cardioResp', models.IntegerField(blank=True, null=True, verbose_name='CardioResp')),
                ('comments', models.TextField(blank=True, help_text='Tell us about your auction.', null=True, verbose_name='Information about the Auction')),
                ('active', models.BooleanField(verbose_name='Active Auction')),
                ('closed', models.BooleanField(verbose_name='Closed Auction')),
                ('deleted', models.BooleanField(verbose_name='Deleted Auction')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Time')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified Time')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_clinic', to='auction.account')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_created_by', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_modified_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DemographicType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a demographic type.', max_length=200, verbose_name='Demographic')),
            ],
        ),
        migrations.CreateModel(
            name='PayFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a pay frequency.', max_length=200, verbose_name='Pay Frequency')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeAreaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a practice area.', max_length=200, verbose_name='Practice Area')),
            ],
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a user type', max_length=200, verbose_name='User Type')),
            ],
        ),
        migrations.CreateModel(
            name='ProMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proStart', models.DateTimeField(verbose_name='Start of Pro Membership')),
                ('proEnd', models.DateTimeField(blank=True, null=True, verbose_name='End of Pro Membership')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_member_clinic', to='auction.account')),
            ],
        ),
        migrations.CreateModel(
            name='PracticeArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percetnage', models.IntegerField(help_text='Enter the percentage your clinic works with the given demographic.', verbose_name='Percentage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_type', to='auction.practiceareatype')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_clinic', to='auction.account')),
            ],
        ),
        migrations.CreateModel(
            name='Demographic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(help_text='Enter the percentage your clinic works with the given demographic.', verbose_name='Percentage')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='auction.demographictype')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demogrpahic_clinic', to='auction.account')),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('bidID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.IntegerField(help_text='Enter the amount you would like to bid.', verbose_name='Amount')),
                ('active', models.BooleanField(verbose_name='Active Bid')),
                ('created', models.DateTimeField(verbose_name='Created Time')),
                ('modified', models.DateTimeField(blank=True, null=True, verbose_name='Modified Time')),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='auction.auction')),
                ('createdBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_created_by', to=settings.AUTH_USER_MODEL)),
                ('modifiedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bid_modified_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='payFrequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_frequency', to='auction.payfrequency'),
        ),
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='demographic',
            field=models.ManyToManyField(blank=True, to='auction.demographic'),
        ),
        migrations.AddField(
            model_name='account',
            name='practiceArea',
            field=models.ManyToManyField(blank=True, to='auction.practicearea'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='account',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertypes', to='auction.usertype', verbose_name='User Type'),
        ),
    ]
