# Generated by Django 4.0.4 on 2022-04-26 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pro',
            field=models.BooleanField(default=False, verbose_name='Pro Member'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionEnd',
            field=models.DateTimeField(help_text='Enter the end date of the auction.', verbose_name='Auction End'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionStart',
            field=models.DateTimeField(help_text='Enter the start date of the auction.', verbose_name='Auction Start'),
        ),
        migrations.CreateModel(
            name='ProMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proStart', models.DateTimeField(verbose_name='Start of Pro Membership')),
                ('proEnd', models.DateTimeField(blank=True, null=True, verbose_name='End of Pro Membership')),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_member_clinic', to='auction.account')),
            ],
        ),
    ]
