# Generated by Django 4.0.4 on 2023-09-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Enter the amount you would like to bid.', null=True, verbose_name='Amount'),
        ),
    ]
