# Generated by Django 4.0.4 on 2022-10-23 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='remember_auction_data',
            field=models.BooleanField(blank=True, null=True, verbose_name='Remember Auction Data'),
        ),
    ]
