# Generated by Django 4.0.4 on 2022-06-17 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='mondayStart',
            field=models.TimeField(blank=True, default='9:00', null=True, verbose_name='Start Time'),
        ),
    ]
