# Generated by Django 4.0.4 on 2022-06-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, choices=[('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan')], default='Ontario', help_text='The province the clinic resides in.', max_length=30, null=True, verbose_name='Province'),
        ),
    ]
