# Generated by Django 4.0.4 on 2026-05-01 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('tickets_required', models.IntegerField(default=1)),
                ('image_icon', models.CharField(default='confirmation_number', help_text='Material icon name', max_length=50)),
                ('value_text', models.CharField(blank=True, help_text='e.g., $50 Value', max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='tickets',
            field=models.IntegerField(default=0, verbose_name='Raffle Tickets'),
        ),
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, help_text='Tell us about your healthcare facility.', null=True, verbose_name='About the healthcare facility'),
        ),
        migrations.AlterField(
            model_name='account',
            name='auction_message_displayed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Listing Message Displayed'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.CharField(blank=True, help_text='Enter the city your healthcare facility is in.', max_length=120, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='clinicName',
            field=models.CharField(blank=True, help_text='Enter the healthcare facility name.', max_length=200, null=True, verbose_name='Clinic Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country your healthcare facility is in.', max_length=100, null=True, verbose_name='Conutry'),
        ),
        migrations.AlterField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut'), ('Yukon', 'Yukon')], help_text='The province the healthcare facility resides in.', max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='account',
            name='remember_auction_data',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you want your data to be pre-populated for your next listing?'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='defaultAuctionLength',
            field=models.IntegerField(help_text='Listing will be set to this length, in seconds.', verbose_name='Default Listing Length in Seconds'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='endAuctionEmailBatchSize',
            field=models.IntegerField(help_text='At the end of an listing emails will be sent to user with the same type as the listing. To avoid spamming email batches are limited to this number.', verbose_name='End of Listing Email Batch Size'),
        ),
        migrations.AlterField(
            model_name='adminsetting',
            name='numAllowedAuctions',
            field=models.IntegerField(help_text='Global setting for max number of active listing', verbose_name='# Allowed Listing'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='active',
            field=models.BooleanField(verbose_name='Active Listing'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='assessmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name="Healthcare facility's Assessment Price"),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionEnd',
            field=models.DateTimeField(help_text='Enter the end date of the listing.', verbose_name='Auction End'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionNumber',
            field=models.IntegerField(blank=True, null=True, verbose_name='Listing Number'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='auctionStart',
            field=models.DateTimeField(help_text='Enter the start date of the listing.', verbose_name='Auction Start'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='closed',
            field=models.BooleanField(verbose_name='Closed Listing'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Information about the healthcare facility'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='deleted',
            field=models.BooleanField(verbose_name='Deleted Listing'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startingBid',
            field=models.IntegerField(blank=True, help_text='The initial bid amount.', null=True, verbose_name='Starting Bid'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='treatmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name="Healthcare facility's Treatment Price"),
        ),
        migrations.AlterField(
            model_name='auction',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auction_type', to='auction.usertype', verbose_name='Listing Type'),
        ),
        migrations.CreateModel(
            name='RaffleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tickets_added', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='auction.raffle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffle_entries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
