# Generated by Django 4.0.4 on 2022-05-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_account_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pro',
            field=models.BooleanField(blank=True, null=True, verbose_name='Pro Member'),
        ),
    ]
