# Generated by Django 4.0.4 on 2026-05-05 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0002_raffle_account_tickets_alter_account_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='tickets',
        ),
        migrations.AddField(
            model_name='account',
            name='numTickets',
            field=models.IntegerField(default=0, help_text='The number of raffle tickets assigned to a user', verbose_name='# of Tickets'),
        ),
        migrations.AddField(
            model_name='raffle',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='numWinningTickets',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='raffle',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_raffles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='raffle',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='raffleentry',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
