# Generated by Django 4.0.4 on 2022-06-27 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_account_msk_alter_account_cardioresp_and_more'),
        ('auction', '0002_alter_auction_mondaystart'),
    ]

    operations = [
    ]
