# Generated by Django 4.0.4 on 2022-04-28 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_account_pro_alter_auction_auctionend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='country',
            field=models.CharField(blank=True, help_text='Enter the country your clinic is in.', max_length=100, null=True, verbose_name='Conutry'),
        ),
        migrations.AlterField(
            model_name='account',
            name='pro',
            field=models.BooleanField(blank=True, verbose_name='Pro Member'),
        ),
        migrations.AlterField(
            model_name='account',
            name='userType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertypes', to='auction.usertype', verbose_name='User Type'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementEnd',
            field=models.DateField(blank=True, help_text='Enter the end date of the placement.', null=True, verbose_name='Placement End'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementStart',
            field=models.DateField(blank=True, help_text='Enter the start date of the placement.', null=True, verbose_name='Placement Start'),
        ),
    ]
