# Generated by Django 4.0.4 on 2022-10-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_account_remember_auction_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='auction_message_displayed',
            field=models.BooleanField(blank=True, null=True, verbose_name='Auction Message Displayed'),
        ),
    ]
