# Generated by Django 4.0.4 on 2023-10-01 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_alter_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='splitCompensation',
            field=models.BooleanField(default=True, help_text='If checked this user type will be allowed to select split compensation as a payment type.', verbose_name='Allowed Split Compensation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(help_text='Enter the amount you would like to bid.', verbose_name='Amount'),
        ),
    ]
