# Generated by Django 4.0.4 on 2022-06-08 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0002_account_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cronIDs',
            field=models.UUIDField(default=1, editable=False, verbose_name='Cron Job Timer ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, help_text='Tell us about your clinic.', null=True, verbose_name='About the clinic'),
        ),
        migrations.AlterField(
            model_name='account',
            name='imageOne',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Upload an image (optional).', null=True, upload_to='images', verbose_name='Clinic Image One'),
        ),
        migrations.AlterField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan')], help_text='The province the clinic resides in.', max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='payFrequency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_frequency', to='auction.payfrequency', verbose_name='Pay Frequency'),
        ),
    ]
