# Generated by Django 4.0.4 on 2022-05-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_account_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created Time'),
        ),
    ]
