# Generated by Django 4.0.4 on 2022-04-29 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_alter_account_country_alter_account_pro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographictype',
            name='properName',
            field=models.CharField(default=5, help_text='Select a demographic type.', max_length=200, verbose_name='Demographic Proper Name'),
            preserve_default=False,
        ),
    ]
