# Generated by Django 4.0.4 on 2022-06-08 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_auction_cronid_alter_account_about_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='cronIDs',
        ),
    ]
