# Generated by Django 4.0.4 on 2026-05-05 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_remove_account_tickets_account_numtickets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='cronID',
            field=models.TextField(blank=True, null=True, verbose_name='Cron Job Timer ID'),
        ),
    ]
