# Generated by Django 4.0.4 on 2023-10-01 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_usertype_splitcompensation_alter_bid_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertype',
            name='splitCompensation',
        ),
        migrations.AddField(
            model_name='usertype',
            name='feeSplit',
            field=models.BooleanField(default=True, help_text='If checked this user type will be allowed to select fee split as a payment type.', verbose_name='Allowed Fee Split'),
            preserve_default=False,
        ),
    ]
