# Generated by Django 4.0.4 on 2023-01-10 02:26

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0003_account_auction_message_displayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(help_text='Name of the page.', max_length=200, verbose_name='Page')),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='remember_auction_data',
            field=models.BooleanField(blank=True, null=True, verbose_name='Do you want your data to be pre-populated for your next auction?'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementEnd',
            field=models.DateField(default=datetime.date.today, help_text='Enter the end date of the placement.', verbose_name='Therapist End Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementStart',
            field=models.DateField(default=datetime.date.today, help_text='Enter the start date of the placement.', verbose_name='Therapist Start Date'),
        ),
        migrations.CreateModel(
            name='PopupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(help_text='Message to be displayed in the popup.', max_length=5000, verbose_name='Popup Message')),
                ('active', models.BooleanField(help_text='Is the popup currently active.', verbose_name='Active')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_popup_message', to='auction.page')),
            ],
        ),
        migrations.CreateModel(
            name='MessageAcknowledgement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acknowledged', models.BooleanField(help_text='Has the popup been acknowledged.', verbose_name='Acknowledged')),
                ('popup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_acknowledgement', to='auction.popupmessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_acknowledgement', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
