# Generated by Django 4.0.4 on 2022-06-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_bid_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Information about the Clinic'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='fridayEnd',
            field=models.TimeField(blank=True, default='17:00', help_text='Enter the end of the workday on Fridays.', null=True, verbose_name='Friday End Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='fridayStart',
            field=models.TimeField(blank=True, default='09:00', help_text='Enter the start of the workday on Fridays.', null=True, verbose_name='Friday Start Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimumBidIncrement',
            field=models.IntegerField(blank=True, help_text='All bids must decrease by the minimum bid increment.', null=True, verbose_name='Minimum Bid Increment'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='mondayEnd',
            field=models.TimeField(blank=True, default='17:00', help_text='Enter the end of the workday on Mondays.', null=True, verbose_name='Monday End Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='mondayStart',
            field=models.TimeField(blank=True, default='09:00', help_text='Enter the start of the workday on Mondays.', null=True, verbose_name='Monday Start Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementEnd',
            field=models.DateField(blank=True, help_text='Enter the end date of the placement.', null=True, verbose_name='Therapist End Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementStart',
            field=models.DateField(blank=True, help_text='Enter the start date of the placement.', null=True, verbose_name='Therapist Start Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='reservePrice',
            field=models.IntegerField(blank=True, help_text='Reserve bid is the maximum price the clinic is willing to offer.', null=True, verbose_name='Reserve Price'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='startingBid',
            field=models.IntegerField(blank=True, help_text='The intial bid amount.', null=True, verbose_name='Starting Bid'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='thursdayEnd',
            field=models.TimeField(blank=True, default='17:00', help_text='Enter the end of the workday on Thursdays.', null=True, verbose_name='Thursday End Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='thursdayStart',
            field=models.TimeField(blank=True, default='09:00', help_text='Enter the start of the workday on Thursdays.', null=True, verbose_name='Thursday Start Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='tuesdayEnd',
            field=models.TimeField(blank=True, default='17:00', help_text='Enter the end of the workday on Tuesdays.', null=True, verbose_name='Tuesday End Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='tuesdayStart',
            field=models.TimeField(blank=True, default='09:00', help_text='Enter the start of the workday on Tuesdays.', null=True, verbose_name='Tuesday Start Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='wednesdayEnd',
            field=models.TimeField(blank=True, default='17:00', help_text='Enter the end of the workday on Wednesdays.', null=True, verbose_name='Wednesday End Time'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='wednesdayStart',
            field=models.TimeField(blank=True, default='09:00', help_text='Enter the start of the workday on Wednesdays.', null=True, verbose_name='Wednesday Start Time'),
        ),
    ]
