# Generated by Django 4.0.4 on 2022-06-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_auction_cronids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cronIDs',
            field=models.CharField(default=1, editable=False, max_length=45, verbose_name='Cron Job Timer ID'),
            preserve_default=False,
        ),
    ]
