# Generated by Django 4.0.4 on 2023-01-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_page_alter_account_remember_auction_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='title',
            field=models.CharField(default='ddd', help_text='The title of the popup box.', max_length=5000, verbose_name='Popup Box Title'),
            preserve_default=False,
        ),
    ]
