# Generated by Django 4.0.4 on 2022-09-10 11:39

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_alter_account_imageone_alter_account_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='imageFour',
            field=models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image Four'),
        ),
        migrations.AlterField(
            model_name='account',
            name='imageOne',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image One'),
        ),
        migrations.AlterField(
            model_name='account',
            name='imageThree',
            field=models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image Three'),
        ),
        migrations.AlterField(
            model_name='account',
            name='imageTwo',
            field=models.ImageField(blank=True, help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('images/'), verbose_name='Clinic Image Two'),
        ),
    ]
