# Generated by Django 4.0.4 on 2026-05-06 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_raffle_cronid'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_ticket_award_date',
            field=models.DateField(blank=True, null=True, verbose_name='Last Ticket Award Date'),
        ),
    ]
