# Generated by Django 4.0.4 on 2023-10-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0004_remove_usertype_splitcompensation_usertype_feesplit'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='adminsettings',
        #     name='defaultAuctionLength',
        #     field=models.IntegerField(default=5000, help_text='Auctions will be set to this length, in seconds.', verbose_name='Default Auction Length in Seconds'),
        #     preserve_default=False,
        # ),
    ]
