# Generated by Django 4.0.4 on 2022-09-10 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_account_imagefour_alter_account_imageone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demogrpahic_auction', to='auction.auction'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='practicearea',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_auction', to='auction.auction'),
            preserve_default=False,
        ),
    ]
