# Generated by Django 4.0.4 on 2022-06-02 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_alter_auction_comments_alter_auction_fridayend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='placementEnd',
            field=models.DateField(help_text='Enter the end date of the placement.', verbose_name='Therapist End Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementStart',
            field=models.DateField(help_text='Enter the start date of the placement.', verbose_name='Therapist Start Date'),
        ),
    ]
