# Generated by Django 4.0.4 on 2023-10-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0005_adminsettings_defaultauctionlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='invoiceNumber1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Invoice Number'),
        ),
    ]
