# Generated by Django 4.0.4 on 2022-06-02 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_alter_auction_placementend_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendEmails', models.BooleanField(help_text='Turns on and off emails. If checked emails will send.', verbose_name='Send Emails')),
                ('numAllowedAuctions', models.IntegerField(help_text='Global setting for max number of active auctions', verbose_name='# Allowed Auctions')),
            ],
        ),
    ]
