# Generated by Django 4.0.4 on 2022-06-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auction_crontimeri'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cronscheduleID',
            field=models.TextField(default=1, editable=False, verbose_name='Cron Job Timer ID'),
            preserve_default=False,
        ),
    ]
