# Generated by Django 4.0.4 on 2023-10-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_auction_invoicenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionNumber1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auction Number'),
        ),
    ]
