# Generated by Django 4.0.4 on 2022-09-10 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0006_remove_demographic_clinic_remove_practicearea_clinic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demogrpahic_clinic', to='auction.account'),
        ),
        migrations.AddField(
            model_name='practicearea',
            name='clinic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_clinic', to='auction.account'),
        ),
    ]
