# Generated by Django 4.0.4 on 2026-05-15 19:42
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0006_account_referral_code_account_referred_by_referral_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='target_audience',
            field=models.CharField(choices=[('Both', 'Both'), ('Clinician', 'Clinician'), ('Clinic', 'Clinic')], default='Both', help_text='Who can see and enter this raffle?', max_length=20),
        ),
    ]