# Generated by Django 4.0.4 on 2023-10-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_auction_invoicenumber1_auction_auctionnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, choices=[('', '----------'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut'), ('Yukon', 'Yukon')], help_text='The province the clinic resides in.', max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='assessmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name='Assessment Cost'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='assessmentMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum # of Assessments'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='treatmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name='Treatment Cost'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='treatmentMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum # of Treatments'),
        ),
    ]
