# Generated by Django 4.0.4 on 2026-05-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_raffle_target_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image for the raffle. If not provided, the Material Icon will be used.', null=True, upload_to='raffle_images/'),
        ),
    ]
