# Generated by Django 4.0.4 on 2022-06-08 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_auction_cronschedulei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='cronIDs',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='cronTimerID',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='cronscheduleID',
        ),
    ]
