# Generated by Django 4.0.4 on 2022-09-10 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0007_remove_demographic_auction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demographic',
            name='clinic',
        ),
        migrations.RemoveField(
            model_name='practicearea',
            name='clinic',
        ),
        migrations.AlterField(
            model_name='demographic',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demogrpahic_auction', to='auction.auction'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='auction',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_auction', to='auction.auction'),
        ),
        migrations.CreateModel(
            name='Demographic2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(help_text='Enter the percentage your clinic works with the given demographic.', verbose_name='Percentage2')),
                ('auction', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='demogrpahic_auction2', to='auction.auction')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category2', to='auction.demographictype')),
            ],
        ),
    ]
