# Generated by Django 4.0.4 on 2022-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_remove_auction_cronids_remove_auction_crontimerid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cronIDs',
            field=models.TextField(default=1, editable=False, verbose_name='Cron Job Timer ID'),
            preserve_default=False,
        ),
    ]
