# Generated by Django 4.0.4 on 2023-10-25 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_rename_auctionnumber1_auction_auctionnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='payFrequency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pay_frequency', to='auction.payfrequency', verbose_name='Pay Frequency'),
        ),
    ]
