# Generated by Django 4.0.4 on 2022-09-10 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_remove_demographic_clinic_remove_practicearea_clinic_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Demographic2',
        ),
    ]
