# Generated by Django 4.2.7 on 2026-07-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_raffle_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='paymentTypes',
            field=models.TextField(blank=True, help_text='Comma-separated list of payment types the clinic offers.', null=True, verbose_name='Payment Types'),
        ),
    ]
