# Generated by Django 4.0.4 on 2023-01-14 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auction', '0008_alter_messageacknowledgement_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageacknowledgement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_message_acknowledgement', to=settings.AUTH_USER_MODEL),
        ),
    ]
