# Generated by Django 4.0.4 on 2023-10-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0008_rename_auctionnumber1_auction_auctionnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='auctionNumber1',
            field=models.IntegerField(blank=True, null=True, verbose_name='Auction Number'),
        )
    ]
