# Generated by Django 4.0.4 on 2023-01-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_alter_messageacknowledgement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupmessage',
            name='show_unauthenticated_users',
            field=models.BooleanField(default=False, help_text='Should the pop-up be shown to non-users.', verbose_name='Show to Non-logged in users.'),
            preserve_default=False,
        ),
    ]
