# Generated by Django 4.2.7 on 2026-07-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_auction_paymenttypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='flatFeeType',
            field=models.CharField(blank=True, choices=[('hourly', 'Hourly'), ('total_contract', 'Total Contract Price')], help_text='Choose how flat-fee offers should be priced.', max_length=50, null=True, verbose_name='Flat Fee Offer Type'),
        ),
    ]
