# Generated by Django 4.0.4 on 2022-09-10 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_delete_demographic2'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicearea',
            name='userType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_user_type', to='auction.usertype'),
        ),
    ]
