# Generated by Django 4.0.4 on 2023-10-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_auction_auctionnumber1_and_more'),
    ]

    operations = [
       migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Select a payment type from the list.', max_length=200, verbose_name='Payment Type')),
            ],
        ),
    ]
