# Generated by Django 4.0.4 on 2023-10-28 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0009_remove_auction_auctionnumber1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='assessmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name="Clinic's Assessment Price"),
        ),
        migrations.AlterField(
            model_name='auction',
            name='assessmentMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Daily Minimum # of Assessments'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='treatmentCost',
            field=models.FloatField(blank=True, null=True, verbose_name="Clinic's Treatment Price"),
        ),
        migrations.AlterField(
            model_name='auction',
            name='treatmentMin',
            field=models.IntegerField(blank=True, null=True, verbose_name='Daily Minimum # of Treatments'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(help_text='Enter the amount you would like to bid.', verbose_name='Amount1'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='auction',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_auction', to='auction.auction'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='practice_area_type', to='auction.practiceareatype'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='percentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Percentage'),
        ),
    ]
