# Generated by GitHub Copilot on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_auction_flatfeetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='offerType',
            field=models.CharField(blank=True, choices=[('Flat Fee', 'Flat Fee'), ('Fee Split', 'Fee Split')], max_length=20, null=True, verbose_name='Offer Type'),
        ),
        migrations.AddField(
            model_name='bid',
            name='submissionGroup',
            field=models.UUIDField(blank=True, null=True, verbose_name='Submission Group'),
        ),
    ]
