# Generated by Django 4.0.4 on 2022-09-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_practicearea_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicearea',
            name='userType',
        ),
    ]
