# Generated by Django 4.0.4 on 2023-10-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0010_remove_auction_auctionnumber1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='Cateogry for the number.', max_length=200, verbose_name='Cateogry')),
                ('currentValue', models.IntegerField(help_text="The counter's current value.", verbose_name='Current Counter Value')),
            ],
        ),
    ]
