# Generated by Django 4.0.4 on 2023-10-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_numbers_remove_auction_auctionnumber1_and_more'),
    ]

    operations = [
        
    ]
