# Generated by Django 4.2.7 on 2026-07-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0011_bid_offertype_bid_submissiongroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='desiredFeeSplitPercentage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Desired Fee Split Percentage'),
        ),
        migrations.AddField(
            model_name='auction',
            name='desiredFlatFeeHourly',
            field=models.IntegerField(blank=True, null=True, verbose_name='Desired Flat Fee Hourly'),
        ),
        migrations.AddField(
            model_name='auction',
            name='desiredFlatFeeTotalContract',
            field=models.IntegerField(blank=True, null=True, verbose_name='Desired Flat Fee Total Contract'),
        ),
    ]
