# Generated by Django 4.2.7 on 2026-07-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_auction_desiredfeesplitpercentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clinicWebsite',
            field=models.URLField(blank=True, help_text='This field is optional. Adding a website may give more traction to your listing.', null=True, verbose_name='Clinic Website'),
        ),
    ]
