# Generated by Django 4.0.4 on 2023-10-28 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_remove_auction_auctionnumber1_and_more'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='Numbers',
        #     new_name='Number',
        # ),
    ]
