# Generated by Django 4.0.4 on 2023-10-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_rename_numbers_number'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='popupmessage',
        #     name='clickID',
        #     field=models.CharField(blank=True, help_text='The ID for the item being clicked to trigger the pop-up. For non-clickable messages leave blank.', max_length=5000, null=True, verbose_name='Clickable Item ID'),
        # ),
    ]
