# Generated by Django 4.2.7 on 2026-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_account_clinicwebsite'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='minimumCompensation',
            field=models.IntegerField(blank=True, null=True, verbose_name='Minimum Compensation'),
        ),
    ]
