# Generated by Django 4.0.4 on 2023-10-31 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_remove_auction_auctionnumber1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='reservePrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Reserve Price'),
        ),
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.IntegerField(blank=True, help_text='Enter the amount you would like to bid.', null=True, verbose_name='Amount1'),
        ),
    ]
