# Generated by Django 4.2.7 on 2026-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_auction_minimumcompensation'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clinicianSkills',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Clinician Skills'),
        ),
        migrations.AddField(
            model_name='auction',
            name='negotiablePerks',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Negotiable Perks Payload'),
        ),
        migrations.AddField(
            model_name='auction',
            name='requiredSkills',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Required Skills Payload'),
        ),
    ]
