# Generated by Django 4.0.4 on 2023-10-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_rename_auctionnumber1_auction_auctionnumber_and_more'),
    ]

    operations = [
    ]
