# Generated by Django 4.2.7 on 2026-07-14 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_account_clinicianskills_auction_negotiableperks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='selectedSkills',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Selected Skills'),
        ),
    ]
