# Generated by Django 4.0.4 on 2023-10-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_rename_auctionnumber1_auction_auctionnumber_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='auctionNumber1',
            new_name='auctionNumber',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='invoiceNumber1',
        ),
    ]
