# Generated by Django 4.0.4 on 2023-11-04 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0016_rename_auctionnumber1_auction_auctionnumber_and_more'),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name='AdminSettings',
        #     new_name='AdminSetting',
        # ),
    ]
