# Generated by Django 5.1.4 on 2024-12-06 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_rename_adminsettings_adminsetting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='auctionNumber1',
            new_name='auctionNumber',
        ),
        migrations.RemoveField(
            model_name='auction',
            name='invoiceNumber1',
        ),
    ]
