# Generated by Django 4.0.4 on 2025-04-19 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0017_rename_adminsettings_adminsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='endAuctionEmailBatchSize',
            field=models.IntegerField(default=1, help_text='At the end of an auction emails will be sent to user with the same type as the auction. To avoid spamming email batches are limited to this number.', verbose_name='End of Auction Email Batch Size'),
            preserve_default=False,
        )
    ]
