# Generated by Django 5.2.1 on 2025-06-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_squashed_0020_adminsetting_rename_numbers_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminsetting',
            name='endAuctionEmailBatchSize',
        ),
    ]
