# Generated by Django 4.2.7 on 2026-07-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0020_adminsetting_defaultclosedwaitingperiodlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='clinicVideo',
            field=models.URLField(blank=True, help_text='This field is optional. Add a YouTube video URL to showcase your clinic.', null=True, verbose_name='Clinic Video'),
        ),
        migrations.AddField(
            model_name='auction',
            name='paymentMethod',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Direct Deposit', 'Direct Deposit'), ('E-Transfer', 'E-Transfer'), ('As part of payroll with other staff', 'As part of payroll with other staff'), ('Other', 'Other'), ("Clinician\'s Choice", "Clinician\'s Choice")], max_length=100, null=True, verbose_name='Payment Method'),
        ),
        migrations.AddField(
            model_name='auction',
            name='paymentMethodOther',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Other Payment Method'),
        ),
        migrations.AddField(
            model_name='auction',
            name='paymentMethodToggle',
            field=models.BooleanField(default=False, verbose_name='Payment Method Toggle'),
        ),
    ]
