# Generated by Django 4.0.4 on 2026-08-05 00:50

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_add_clinicvideo_and_paymentmethod_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='clinicWebsite',
            field=models.URLField(blank=True, help_text='This field is optional. Adding a website may give more traction to your listing - your website will be linked in your listings.', null=True, verbose_name='Clinic Website'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='currentLowBid',
            field=models.IntegerField(blank=True, null=True, verbose_name='Current Winning Offer'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='minimumBidIncrement',
            field=models.IntegerField(blank=True, help_text='Each new winning offer must improve by at least this amount.', null=True, verbose_name='Winning Offer Step'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementEnd',
            field=models.DateField(default=auction.models.get_default_end_date, help_text='Enter the end date of the placement.', verbose_name='Clinican End Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='placementStart',
            field=models.DateField(default=auction.models.get_default_start_date, help_text='Enter the start date of the placement.', verbose_name='Clinican Start Date'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='winningPrice',
            field=models.IntegerField(blank=True, null=True, verbose_name='Winning Offer'),
        ),
    ]
