# Generated by Django 5.2.1 on 2025-06-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0021_remove_adminsetting_endauctionemailbatchsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsetting',
            name='endAuctionEmailBatchSize',
            field=models.IntegerField(default=2, help_text='At the end of an auction emails will be sent to user with the same type as the auction. To avoid spamming email batches are limited to this number.', verbose_name='End of Auction Email Batch Size'),
            preserve_default=False,
        ),
    ]
