# Generated by Django 4.0.4 on 2022-06-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='MSK',
            field=models.IntegerField(blank=True, null=True, verbose_name='% Musculoskeletal'),
        ),
        migrations.AlterField(
            model_name='account',
            name='cardioResp',
            field=models.IntegerField(blank=True, null=True, verbose_name='% Cardiorespiratory'),
        ),
        migrations.AlterField(
            model_name='account',
            name='eighteenToSixtyFive',
            field=models.IntegerField(blank=True, null=True, verbose_name='% 18 - 65'),
        ),
        migrations.AlterField(
            model_name='account',
            name='neuro',
            field=models.IntegerField(blank=True, null=True, verbose_name='% Neurological'),
        ),
        migrations.AlterField(
            model_name='account',
            name='overSixtyFive',
            field=models.IntegerField(blank=True, null=True, verbose_name='% Over 65'),
        ),
        migrations.AlterField(
            model_name='account',
            name='underEighteen',
            field=models.IntegerField(blank=True, null=True, verbose_name='% Under 18'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='mondayStart',
            field=models.TimeField(blank=True, default='9:00', null=True, verbose_name='Start Time'),
        ),
    ]
