# Generated by Django 4.0.4 on 2022-06-27 09:19

import auction.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0003_merge_20220627_0515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='imageOne',
            field=models.ImageField(blank=True, default='default.jpg', help_text='Upload an image (optional).', null=True, upload_to=auction.models.PathAndRename('/images'), verbose_name='Clinic Image One'),
        ),
        migrations.AlterField(
            model_name='account',
            name='province',
            field=models.CharField(blank=True, choices=[('', '---------'), ('Alberta', 'Alberta'), ('British Columbia', 'British Columbia'), ('Manitoba', 'Manitoba'), ('New Brunswick', 'New Brunswick'), ('Newfoundland and Labrador', 'Newfoundland and Labrador'), ('Nova Scotia', 'Nova Scotia'), ('Ontario', 'Ontario'), ('Prince Edward Island', 'Prince Edward Island'), ('Quebec', 'Quebec'), ('Saskatchewan', 'Saskatchewan'), ('Northwest Territories', 'Northwest Territories'), ('Nunavut', 'Nunavut'), ('Yukon', 'Yukon')], help_text='The province the clinic resides in.', max_length=30, null=True, verbose_name='Province'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='mondayStart',
            field=models.TimeField(blank=True, default='09:00', null=True, verbose_name='Start Time'),
        ),
    ]
