# Generated by Django 4.0.4 on 2022-09-10 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0012_practiceareatype_usertype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='practicearea',
            old_name='percetnage',
            new_name='percentage',
        ),
    ]
