# Generated by Django 4.0.4 on 2022-10-04 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0013_rename_percetnage_practicearea_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic',
            name='percentage',
            field=models.IntegerField(verbose_name='Percentage'),
        ),
        migrations.AlterField(
            model_name='practicearea',
            name='percentage',
            field=models.IntegerField(verbose_name='Percentage'),
        ),
    ]
