# Generated by Django 4.0.4 on 2022-10-23 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0014_alter_demographic_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='type1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auction_type', to='auction.usertype', verbose_name='Auction Type'),
            preserve_default=1,
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(help_text='Select a therapist type', max_length=200, verbose_name='Therapist Type'),
        ),
    ]
