# Generated by Django 4.0.4 on 2022-10-23 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auction', '0015_auction_type_alter_usertype_name'),
    ]

    operations = [
        
    ]
